name: Build and Publish

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            artifact: darwin-arm64
          - os: windows-latest
            artifact: win32-x64
          - os: ubuntu-latest
            artifact: linux-x64

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install Linux X11 headers
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libx11-dev libxrandr-dev libxtst-dev

      - name: Disable Windows Defender for quicker build times
        if: runner.os == 'Windows'
        shell: powershell
        run: Add-MpPreference -ExclusionPath "${{ github.workspace }}"

      - name: Install NPM build dependencies
        run: npm install

      - name: Build NPM module
        run: npm run build

      - name: Verify build output
        run: test -f prebuilds/${{ matrix.artifact }}/node.napi.node

      - name: Upload build output as an artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact }}
          path: prebuilds/${{ matrix.artifact }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Download all build output artifacts
        uses: actions/download-artifact@v7
        with:
          path: prebuilds
          merge-multiple: false

      - name: Show downloaded structure
        run: find prebuilds -type f

      - name: Upload all build outputs to NPM
        run: npm publish --provenance --access public